name: Terraform Azure Fabric Automation

on:
  workflow_dispatch: # execução manual
  push:
    branches:
      - main
      - develop

env:
  TF_ROOT: ./envs

jobs:
  terraform:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [dev, pre, prd]

    defaults:
      run:
        working-directory: ${{ env.TF_ROOT }}/${{ matrix.environment }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.7

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars"

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch'
        run: terraform apply -auto-approve -var-file="terraform.tfvars"
